// Core session management

// Config paths
export { getAgentDir, VERSION } from "./config.js";
export {
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type ModelCycleResult,
	type ParsedSkillBlock,
	type PromptOptions,
	parseSkillBlock,
	type SessionStats,
} from "./core/agent-session.js";
// Auth and model registry
export {
	type ApiKeyCredential,
	type AuthCredential,
	AuthStorage,
	type AuthStorageBackend,
	FileAuthStorageBackend,
	InMemoryAuthStorageBackend,
	type OAuthCredential,
} from "./core/auth-storage.js";
// Compaction
export {
	type BranchPreparation,
	type BranchSummaryResult,
	type CollectEntriesResult,
	type CompactionResult,
	type CutPointResult,
	calculateContextTokens,
	collectEntriesForBranchSummary,
	compact,
	DEFAULT_COMPACTION_SETTINGS,
	estimateTokens,
	type FileOperations,
	findCutPoint,
	findTurnStartIndex,
	type GenerateBranchSummaryOptions,
	generateBranchSummary,
	generateSummary,
	getLastAssistantUsage,
	prepareBranchEntries,
	serializeConversation,
	shouldCompact,
} from "./core/compaction/index.js";
export { createEventBus, type EventBus, type EventBusController } from "./core/event-bus.js";
// Extension system
export type {
	AgentEndEvent,
	AgentStartEvent,
	AgentToolResult,
	AgentToolUpdateCallback,
	AppAction,
	BashToolCallEvent,
	BeforeAgentStartEvent,
	CompactOptions,
	ContextEvent,
	ContextUsage,
	CustomToolCallEvent,
	EditToolCallEvent,
	ExecOptions,
	ExecResult,
	Extension,
	ExtensionActions,
	ExtensionAPI,
	ExtensionCommandContext,
	ExtensionCommandContextActions,
	ExtensionContext,
	ExtensionContextActions,
	ExtensionError,
	ExtensionEvent,
	ExtensionFactory,
	ExtensionFlag,
	ExtensionHandler,
	ExtensionRuntime,
	ExtensionShortcut,
	ExtensionUIContext,
	ExtensionUIDialogOptions,
	ExtensionWidgetOptions,
	FindToolCallEvent,
	GrepToolCallEvent,
	InputEvent,
	InputEventResult,
	InputSource,
	KeybindingsManager,
	LoadExtensionsResult,
	LsToolCallEvent,
	MessageRenderer,
	MessageRenderOptions,
	ProviderConfig,
	ProviderModelConfig,
	ReadToolCallEvent,
	RegisteredCommand,
	RegisteredTool,
	SessionBeforeCompactEvent,
	SessionBeforeForkEvent,
	SessionBeforeSwitchEvent,
	SessionBeforeTreeEvent,
	SessionCompactEvent,
	SessionForkEvent,
	SessionShutdownEvent,
	SessionStartEvent,
	SessionSwitchEvent,
	SessionTreeEvent,
	SlashCommandInfo,
	SlashCommandLocation,
	SlashCommandSource,
	TerminalInputHandler,
	ToolCallEvent,
	ToolDefinition,
	ToolInfo,
	ToolRenderResultOptions,
	ToolResultEvent,
	TurnEndEvent,
	TurnStartEvent,
	UserBashEvent,
	UserBashEventResult,
	WidgetPlacement,
	WriteToolCallEvent,
} from "./core/extensions/index.js";
export {
	createExtensionRuntime,
	discoverAndLoadExtensions,
	ExtensionRunner,
	isBashToolResult,
	isEditToolResult,
	isFindToolResult,
	isGrepToolResult,
	isLsToolResult,
	isReadToolResult,
	isToolCallEventType,
	isWriteToolResult,
	wrapRegisteredTool,
	wrapRegisteredTools,
	wrapToolsWithExtensions,
	wrapToolWithExtensions,
} from "./core/extensions/index.js";
// Footer data provider (git branch + extension statuses - data not otherwise available to extensions)
export type { ReadonlyFooterDataProvider } from "./core/footer-data-provider.js";
export { convertToLlm } from "./core/messages.js";
export {
	getMcpCommandHelp,
	getMcpConfigPath,
	getMergedServerByName,
	loadMergedMcpConfig,
	McpRuntime,
	parseMcpAddCommand,
	parseMcpTargetCommand,
} from "./core/mcp/index.js";
export type {
	McpConfigFile,
	McpResolvedServerConfig,
	McpScope,
	McpScopeTarget,
	McpServerConfig,
	McpServerStatus,
	McpTransport,
} from "./core/mcp/index.js";
export { ModelRegistry } from "./core/model-registry.js";
export type {
	PackageManager,
	PathMetadata,
	ProgressCallback,
	ProgressEvent,
	ResolvedPaths,
	ResolvedResource,
} from "./core/package-manager.js";
export { DefaultPackageManager } from "./core/package-manager.js";
export type { ResourceCollision, ResourceDiagnostic, ResourceLoader } from "./core/resource-loader.js";
export { DefaultResourceLoader } from "./core/resource-loader.js";
// SDK for programmatic usage
export {
	type CreateAgentSessionOptions,
	type CreateAgentSessionResult,
	// Factory
	createAgentSession,
	createAskUserTool,
	createBashTool,
	// Tool factories (for custom cwd)
	createCodingTools,
	createCombyTool,
	createEditTool,
	createFdTool,
	createFindTool,
	createGrepTool,
	createJqTool,
	createLsTool,
	createReadOnlyTools,
	createReadTool,
	createRgTool,
	createSedTool,
	createSemanticSearchTool,
	createSemgrepTool,
	createAstGrepTool,
	createWriteTool,
	createYqTool,
	type PromptTemplate,
	// Pre-built tools (use process.cwd())
	readOnlyTools,
} from "./core/sdk.js";
export {
	type BranchSummaryEntry,
	buildSessionContext,
	type CompactionEntry,
	CURRENT_SESSION_VERSION,
	type CustomEntry,
	type CustomMessageEntry,
	type FileEntry,
	getLatestCompactionEntry,
	type ModelChangeEntry,
	migrateSessionEntries,
	type NewSessionOptions,
	parseSessionEntries,
	type SessionContext,
	type SessionEntry,
	type SessionEntryBase,
	type SessionHeader,
	type SessionInfo,
	type SessionInfoEntry,
	SessionManager,
	type SessionMessageEntry,
	type ThinkingLevelChangeEntry,
} from "./core/session-manager.js";
export {
	type CompactionSettings,
	type ImageSettings,
	type PackageSource,
	type RetrySettings,
	SettingsManager,
} from "./core/settings-manager.js";
// Skills
export {
	formatSkillsForPrompt,
	type LoadSkillsFromDirOptions,
	type LoadSkillsResult,
	loadSkills,
	loadSkillsFromDir,
	type Skill,
	type SkillFrontmatter,
} from "./core/skills.js";
// Tools
export {
	type SemanticSearchToolInput,
	type SemanticSearchToolOptions,
	type BashOperations,
	type BashSpawnContext,
	type BashSpawnHook,
	type BashToolDetails,
	type BashToolInput,
	type BashToolOptions,
	type CombyToolInput,
	type AstGrepToolInput,
	type ExternalCliToolDetails,
	type ExternalCliToolInput,
	type ExternalCliToolOptions,
	type FdToolInput,
	type JqToolInput,
	type RgToolInput,
	type SedToolInput,
	type SemgrepToolInput,
	type YqToolInput,
	astGrepTool,
	bashTool,
	codingTools,
	combyTool,
	DEFAULT_MAX_BYTES,
	DEFAULT_MAX_LINES,
	type EditOperations,
	type EditToolDetails,
	type EditToolInput,
	type EditToolOptions,
	editTool,
	type FindOperations,
	type FindToolDetails,
	type FindToolInput,
	type FindToolOptions,
	fdTool,
	findTool,
	formatSize,
	type GrepOperations,
	type GrepToolDetails,
	type GrepToolInput,
	type GrepToolOptions,
	grepTool,
	jqTool,
	type LsOperations,
	type LsToolDetails,
	type LsToolInput,
	type LsToolOptions,
	lsTool,
	rgTool,
	type ReadOperations,
	type ReadToolDetails,
	type ReadToolInput,
	type ReadToolOptions,
	readTool,
	sedTool,
	semanticSearchTool,
	semgrepTool,
	type ToolsOptions,
	type TruncationOptions,
	type TruncationResult,
	truncateHead,
	truncateLine,
	truncateTail,
	type WriteOperations,
	type WriteToolInput,
	type WriteToolOptions,
	writeTool,
	yqTool,
	createExternalCliTool,
} from "./core/tools/index.js";
export type {
	SemanticAction,
	SemanticConfigFile,
	SemanticIndexConfig,
	SemanticIndexMeta,
	SemanticIndexOperationResult,
	SemanticMergedConfig,
	SemanticProviderConfig,
	SemanticProviderType,
	SemanticQueryHit,
	SemanticQueryResult,
	SemanticScope,
	SemanticScopedLoadResult,
	SemanticSearchConfig,
	SemanticStatusResult,
	SemanticStaleReason,
	SemanticToolResult,
} from "./core/semantic/index.js";
export {
	SemanticConfigError,
	SemanticConfigMissingError,
	SemanticRebuildRequiredError,
	SemanticSearchRuntime,
	createSemanticEmbeddingProvider,
	getDefaultSemanticSearchConfig,
	getSemanticConfigPath,
	getSemanticIndexDir,
	getSemanticIndexFiles,
	getSemanticIndexesDir,
	getSemanticProjectHash,
	getSemanticRootDir,
	loadMergedSemanticConfig,
	loadSemanticIndex,
	readScopedSemanticConfig,
	upsertScopedSemanticSearchConfig,
	writeScopedSemanticConfig,
	writeSemanticIndex,
	clearSemanticIndex,
} from "./core/semantic/index.js";
// Main entry point
export { main } from "./main.js";
// Run modes for programmatic SDK usage
export {
	InteractiveMode,
	type InteractiveModeOptions,
	type PrintModeOptions,
	runPrintMode,
	runRpcMode,
} from "./modes/index.js";
// UI components for extensions
export {
	ArminComponent,
	AssistantMessageComponent,
	appKey,
	appKeyHint,
	BashExecutionComponent,
	BorderedLoader,
	BranchSummaryMessageComponent,
	CompactionSummaryMessageComponent,
	CustomEditor,
	CustomMessageComponent,
	DynamicBorder,
	ExtensionEditorComponent,
	ExtensionInputComponent,
	ExtensionSelectorComponent,
	editorKey,
	FooterComponent,
	keyHint,
	LoginDialogComponent,
	McpSelectorComponent,
	ModelSelectorComponent,
	OAuthSelectorComponent,
	type McpSelectorCallbacks,
	type RenderDiffOptions,
	rawKeyHint,
	renderDiff,
	SessionSelectorComponent,
	type SettingsCallbacks,
	type SettingsConfig,
	SettingsSelectorComponent,
	ShowImagesSelectorComponent,
	SkillInvocationMessageComponent,
	ThemeSelectorComponent,
	ThinkingSelectorComponent,
	ToolExecutionComponent,
	type ToolExecutionOptions,
	TreeSelectorComponent,
	truncateToVisualLines,
	UserMessageComponent,
	UserMessageSelectorComponent,
	type VisualTruncateResult,
} from "./modes/interactive/components/index.js";
// Theme utilities for custom tools and extensions
export {
	getLanguageFromPath,
	getMarkdownTheme,
	getSelectListTheme,
	getSettingsListTheme,
	highlightCode,
	initTheme,
	Theme,
	type ThemeColor,
} from "./modes/interactive/theme/theme.js";
// Clipboard utilities
export { copyToClipboard } from "./utils/clipboard.js";
export { parseFrontmatter, stripFrontmatter } from "./utils/frontmatter.js";
// Shell utilities
export { getShellConfig } from "./utils/shell.js";
// IOSM helpers
export {
	assessDeclineCoverage,
	buildCycleBudget,
	calculateDecisionConfidence,
	calculateIosmIndex,
	calculateIosmMetricsFromRawMeasurements,
	calculateMetricDeltas,
	clamp01,
	createMetricRecord,
	findIosmRootDir,
	type IosmCycleCapacityReport,
	type IosmCycleHistoryRecordResult,
	type IosmCycleListItem,
	type IosmCycleReport,
	type IosmCycleScope,
	type IosmCycleStatus,
	type IosmDecision,
	type IosmEvidenceTier,
	type IosmConfig,
	type IosmConfigModel,
	type IosmHypothesisCard,
	type IosmHypothesisOutcome,
	type IosmInitOptions,
	type IosmInitResult,
	type IosmMetric,
	type IosmMetricRecord,
	type IosmPhase,
	type IosmPhaseReport,
	hasCompleteNumericMetricRecord,
	hasCompleteTierMetricRecord,
	inspectIosmCycle,
	IOSM_METRICS,
	type PlannedIosmCycle,
	getIosmBaselinesDir,
	getIosmBaselineReportPath,
	getIosmConfigPath,
	getIosmContractCatalogPath,
	getIosmCycleDir,
	getIosmCycleReportPath,
	getIosmCyclesDir,
	getIosmDecisionLogPath,
	getIosmHypothesesPath,
	getIosmInvariantCatalogPath,
	getIosmMetricsHistoryPath,
	getIosmPatternLibraryPath,
	getIosmPhaseReportPath,
	getIosmPhaseReportsDir,
	getIosmWaiverRegisterPath,
	getIosmWorkspaceDir,
	initIosmWorkspace,
	listIosmCycles,
	loadIosmConfig,
	mergeMetricValues,
	normalizeHigherIsBetter,
	normalizeLowerIsBetter,
	planIosmCycle,
	recordIosmCycleHistory,
	readIosmCycleReport,
	resolveIosmRootDir,
	validateGuardrails,
} from "./iosm/index.js";
